ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5433
      dbname: ecommerce
      schema: public
      threads: 4
