ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5433
      dbname: ecommerce
      schema: public
      threads: 4
    bigquery:
      type: bigquery
      method: oauth
      project: exalted-cogency-499917-n4
      dataset: ecommerce
      threads: 4
      location: US
