ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'admin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'admin') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      schema: public
      threads: 4
    athena:
      type: athena
      s3_staging_dir: "{{ env_var('ATHENA_S3_STAGING_DIR') }}"
      s3_data_dir: "s3://{{ env_var('S3_BUCKET_NAME') }}/analytics/"
      region_name: "{{ env_var('AWS_REGION', 'us-east-1') }}"
      database: "{{ env_var('ATHENA_DATABASE', 'ecommerce_raw') }}"
      schema: analytics
      threads: 4

